#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Passwords101_Android.Resource", IsApplication=true)]

namespace Passwords101_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int autoCompleteTextView1 = 2131034115;
			
			// aapt resource value: 0x7f050013
			public const int buttonCopyResult = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int buttonGeneratePassword = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int editTextMasterPassword = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int editTextMaxLength = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int editTextSpecialChar = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int labelHashCheck = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int labelInput = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int labelMaxLength = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int labelPassword = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int labelResult = 2131034129;
			
			// aapt resource value: 0x7f050005
			public const int labelSpecialChar = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int labelSpecialCharInput = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout1 = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout2 = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int progressBar1 = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int switch1 = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int textViewHashCheck = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int textViewPasswordResult = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int textView = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000b
			public const int app_name = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int buttonCopy = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int buttonGenerate = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int labelCheck = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int labelCheckEmpty = 2130968586;
			
			// aapt resource value: 0x7f040000
			public const int labelInput = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int labelInputPlaceholder = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int labelMasterPassword = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int labelMaxLength = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int labelPasswordResult = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int labelSpecialChar = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int labelSpecialCharToggle = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
